version: '3.1'
services:

  # Database Service
  postgres:
#    build: ../postgres
    image: polymorphicfox/geo-data-db:latest
    container_name: "my_postgres"
    ports:
      - "5432:5432"
    environment:
#      POSTGRES_DB: geo_objects_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root