version: '3.1'
services:
  test-service:
#    build: ../../test-service/src/main/docker
    image: polymorphicfox/test-service:latest
    container_name: "backend_app"
    restart: always
    links:
      - postgres
    depends_on:
      - postgres
    expose:
      - 8080
    ports:
      - "8080:8080"
#    networks:
#      - backend
#      - frontend

#  #Geo clustering frontend
  clustering-frontend:
#    build: ../../client
    image: polymorphicfox/clustering-app-frontend:latest
    container_name: "frontend_app"
    depends_on:
      - test-service
    links:
      - test-service
    ports:
      - "9090:80"
#    networks:
#      - frontend

  # Database Service
  postgres:
#    build: ../postgres
    image: polymorphicfox/geo-data-db:latest
    container_name: "postgres_db"
    expose:
      - 5432
    ports:
      - "5432:5432"
    environment:
#      POSTGRES_DB: geo_objects_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
#    networks:
#      - backend

#networks:
#  backend:
#  frontend: