version: '3.1'
services:
  test-service:
#    build: ../../test-service/src/main/docker
    image: polymorphicfox/test-service:latest
    ports:
      - "8080:8080"
    networks:
      - backend
      - frontend

  #Geo clustering frontend
  clustering-frontend:
#    build: ../../client
    image: polymorphicfox/clustering-app-frontend:latest
    ports:
      - "9090:80"
    networks:
      - frontend

networks:
  backend:
  frontend:

  # Database Service