version: '3.1'
services:
  test-service:
#    build: ../../test-service/src/main/docker
    image: polymorphicfox/test-service:latest
    ports:
      - "8080:8080"
    networks:
      - backend
      - frontend

  #Geo clustering frontend
  clustering-frontend:
#    build: ../../client
    image: polymorphicfox/clustering-app-frontend:latest
    ports:
      - "9090:80"
    networks:
      - frontend

  # Database Service
  postgres:
#    build: ../postgres
    image: polymorphicfox/geo-data-db:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: halva
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    networks:
      - backend

networks:
  backend:
  frontend: